name: 'Commit: Build and push image to puppet-artifacts Google Artifact Registry'
on:
  push:
    branches:
      - main
jobs:
  release:
    env:
      ARTIFACT_REGISTRY_PATH: 'us-west1-docker.pkg.dev/puppet-artifacts/community-ecosystem'
      IMAGE_NAME: 'puppet-validator'
      IMAGE_TAG: ${GITHUB_SHA}
      PUBLISHER_PREFIX: 'community-ecosystem'
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build --build-arg GITHUB_SHA -t "${{ env.ARTIFACT_REGISTRY_PATH }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" ./build
      - name: Build alpine image
        run: docker build --build-arg GITHUB_SHA -t "${{ env.ARTIFACT_REGISTRY_PATH }}/${{ env.IMAGE_NAME }}-alpine:${{ env.IMAGE_TAG }}" -f build/Dockerfile.alpine ./build
      - id: google-auth
        uses: google-github-actions/auth@v0
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/427026933618/locations/global/workloadIdentityPools/puppet-artifacts/providers/github'
          service_account: '${{ env.PUBLISHER_PREFIX }}-publisher@puppet-artifacts.iam.gserviceaccount.com'
      - name: Authenticate to Google Artifact Registry and push image
        run: |
          gcloud --quiet auth configure-docker us-west1-docker.pkg.dev
          docker push ${{ env.ARTIFACT_REGISTRY_PATH }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - name: Push alpine image
        run:
          docker push ${{ env.ARTIFACT_REGISTRY_PATH }}/${{ env.IMAGE_NAME }}-alpine:${{ env.IMAGE_TAG }}
